create table if not exists sword (id integer primary key autoincrement, name VARCHAR(50), speciality VARCHAR(70), damage INT);
insert into sword (id, name, speciality, damage) values (1, 'Sisterhood of the Traveling Pants 2, The', 'Waxbill, violet-eared', 48);
insert into sword (id, name, speciality, damage) values (2, 'Hudson Hawk', 'Dolphin, bottle-nose', 89);
insert into sword (id, name, speciality, damage) values (3, 'Futurama: Bender''s Game', 'Hawk-headed parrot', 99);
insert into sword (id, name, speciality, damage) values (4, 'Witch Hunt', 'Javan gold-spotted mongoose', 100);
insert into sword (id, name, speciality, damage) values (5, 'True Grit', 'Lizard, blue-tongued', 73);
insert into sword (id, name, speciality, damage) values (6, 'Stevie Nicks: Live at Red Rocks', 'Stork, greater adjutant', 52);
insert into sword (id, name, speciality, damage) values (7, 'Gifted Hands: The Ben Carson Story', 'Siskin, yellow-rumped', 71);
insert into sword (id, name, speciality, damage) values (8, 'Million to Juan, A', 'Yellow mongoose', 100);
insert into sword (id, name, speciality, damage) values (9, 'Return of the Killer Tomatoes!', 'Prehensile-tailed porcupine', 7);
insert into sword (id, name, speciality, damage) values (10, 'Chasers', 'Boa, mexican', 53);
insert into sword (id, name, speciality, damage) values (11, 'Summer Holiday', 'Monitor, water', 6);
insert into sword (id, name, speciality, damage) values (12, 'Life and Adventures of Santa Claus, The', 'Masked booby', 30);
insert into sword (id, name, speciality, damage) values (13, '20 Million Miles to Earth', 'Crested porcupine', 52);
insert into sword (id, name, speciality, damage) values (14, 'Lawless Breed, The', 'Cat, civet', 45);
insert into sword (id, name, speciality, damage) values (15, 'Fire of Conscience (For lung)', 'Snowy owl', 56);
insert into sword (id, name, speciality, damage) values (16, 'Green Card', 'Nutcracker, clark''s', 88);
insert into sword (id, name, speciality, damage) values (17, 'Art of the Steal, The', 'Squirrel, european red', 5);
insert into sword (id, name, speciality, damage) values (18, 'CJ7 (Cheung Gong 7 hou)', 'Starling, greater blue-eared', 91);
insert into sword (id, name, speciality, damage) values (19, 'Cinderella Liberty', 'Huron', 78);
insert into sword (id, name, speciality, damage) values (20, 'Storm Catcher', 'Levaillant''s barbet', 55);
insert into sword (id, name, speciality, damage) values (21, 'My Little Chickadee', 'Common wallaroo', 27);
insert into sword (id, name, speciality, damage) values (22, 'Debut, The', 'Wild water buffalo', 4);
insert into sword (id, name, speciality, damage) values (23, 'Iron Jawed Angels', 'Common mynah', 1);
insert into sword (id, name, speciality, damage) values (24, 'Gozu (Gokudô kyôfu dai-gekijô: Gozu)', 'Vulture, black', 33);
insert into sword (id, name, speciality, damage) values (25, 'Life in Flight ', 'Fox, cape', 71);
insert into sword (id, name, speciality, damage) values (26, 'Fist of Legend (Jing wu ying xiong)', 'Red lava crab', 66);
insert into sword (id, name, speciality, damage) values (27, 'April Fool''s Day', 'Huron', 46);
insert into sword (id, name, speciality, damage) values (28, 'Tyler Perry''s Madea''s Family Reunion', 'Grenadier, common', 98);
insert into sword (id, name, speciality, damage) values (29, 'Year of the Comet', 'Long-billed cockatoo', 11);
insert into sword (id, name, speciality, damage) values (30, 'I Wish (Kiseki)', 'Beaver, north american', 86);